### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [Yaanu/h-de-vere-stacpoole_the-blue-lagoon#1]
# General Issues:

- [x] Re-run `se clean .` and commit the changes.

- [x] Re-run `se typogrify .` and commit the changes.

- [x] Since you have illustrations in the production, you need to add an LOI ([SEMOS 7.9](https://standardebooks.org/manual/1.8.0/single-page#7.9)).

- [x] You need to include the source JPGs/PNGs used to make the SVGs in the `./images` file.

- [x] Instead of naming the files `butten.svg`, `henry2.svg`, etc., they should be named `illustration-1.svg`, `illustration-2.svg`, etc. ([SEMOS 2.2.5](https://standardebooks.org/manual/1.8.0/single-page#2.2.5)).

- [x] **After all of the other changes have been made**, re-run `se build-manifest .`, `se build-spine .`, and `se build-toc .`

# chapter-1-1-1.xhtml:

- [x] In the song, convert the `<i>` elements to `<em>`s.

# chapter-1-1-2.xhtml:

- [x] Remove the italics around `con amore`.

# chapter-1-1-4.xhtml:

- [x] In the second paragraph, the dash in `H⁠—l!` needs to be a two-em dash ([SEMOS 8.7.7.8.4.1](https://standardebooks.org/manual/1.8.0/single-page#8.7.7.8.4.1)).

- [x] For `<i>through</i>`, convert the `<i>` to `<em>`.

# chapter-1-1-8.xhtml:

- [x] Since the title is being spelled out, the individual letters need to be marked as graphemes ([SEMOS 8.2.8.2.1](https://standardebooks.org/manual/1.8.0/single-page#8.2.8.2.1)).

# chapter-1-1-9.xhtml:

- [x] For `<i>could</i>` and `<i>its</i>`, convert the `<i>`s to `<em>`s.

# chapter-1-2-11.xhtml:

- [x] For `<i>tight</i>`, convert the `<i>` to `<em>`.

# chapter-1-3-16.xhtml:

- [x] For `<i>with</i>`, convert the `<i>` to `<em>`.

# chapter-1-3-18.xhtml:

- [x] In the page scans, the line `The niggers are all set free.”` is on a separate line with a large indent. It looks like `class="i7` would work.

In the song, `Chorus` is a persona. I recommend formatting the whole blockquote as drama. It would look something like:
```
			<blockquote epub:type="z3998:song">
				<table epub:type="z3998:drama">
					<tbody>
						<tr>
							<td/>
							<td>
								<p>
									<span>“There were five or six old drunken sailors</span>
									<br/>
									<span class="i1">Standin’ before the bar,</span>
									<br/>
									<span>And Larry, he was servin’ them</span>
									<br/>
									<span class="i1">From a big five-gallon jar.</span>
								</p>
							</td>
						</tr>
						<tr>
							<td epub:type="z3998:persona">Chorus</td>
							<td>
								<p>
									<span>“Hoist up the flag, long may it wave!</span>
									<br/>
									<span class="i1">Long may it lade us to glory or the grave.</span>
									<br/>
									<span>Stidy, boys, stidy⁠—sound the jubilee,</span>
									<br/>
									<span class="i1">For Babylon has fallen, and</span>
									<br/>
									<span class="i7">The niggers are all set free.”</span>
								</p>
							</td>
						</tr>
					</tbody>
				</table>
			</blockquote>
```

# chapter-2-2-12.xhtml:

- [x] In the title, `continued` needs to be capitalized.

# chapter-3-4.xhtml:

- [x] For `<i>finesse</i>`, convert the `<i>` to `<em>`.

# local.css:

- [x] **After making the above changes**, you will need to add CSS drama and song indentation.

# content.opf:

- [x] Since many of the book subjects include the word "Fiction", it would be a good idea to add the SE subject `Fiction`.
